title: Metastable States in Driven Nonlinear Systems
description: Research documentation on quantum activation and switching dynamics in driven nonlinear oscillators
theme: jekyll-theme-cayman

# Show downloads
show_downloads: true

# Enable MathJax for LaTeX support
markdown: kramdown
kramdown:
  math_engine: mathjax

# Navigation
nav:
  - Overview: /derivation/Overview
  - Original EoM: /derivation/OriginalEom
  - Keldysh Lagrangian: /derivation/KeldyshLagrangian
  - Keldysh Auxiliary Hamiltonian: /derivation/KeldyshAuxiliaryHamiltonian
  - Fixed Points: /fixed_points/FixedPoints
  - Stability Analysis: /fixed_points/StabilityAnalysis
  - Paths: /paths/Paths

exclude:
  - "**/*.npz"    # Excludes all NPZ files in any directory