name: Generate Notebooks

on:
  push:
    paths:
      - 'explain/*.md'

jobs:
  convert-notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Make scripts executable
      run: chmod +x scripts/md_to_notebook.py
    
    - name: Generate notebooks
      run: ./scripts/md_to_notebook.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add notebooks/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate notebooks from markdown files" && git push) 